version: '3'

services:
  web:
    image: tomcat
    volumes:
      - ./target/${WAR_FILE:-app}.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql